apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: orders-ms
    spec:
      containers:
        - image: orders-ms
          name: orders-ms
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: database_url
                  name: orders-secrets
          resources: {}
status: {}
