apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: payments-ms
  name: payments-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: payments-ms
    spec:
      containers:
        - image: payments-ms
          name: payments-ms
          imagePullPolicy: Never
          env:
            - name: PORT
              value: "3000"
            - name: NATS_SERVERS
              value: "nats://nats:4222"
            - name: SUCCESS_URL
              value: "http://localhost:3000/payments/success"
            - name: CANCEL_URL
              value: "http://localhost:3000/payments/cancel"
            - name: STRIPE_SECRET
              valueFrom:
                secretKeyRef:
                  key: STRIPE_SECRET
                  name: payments-secrets
            - name: STRIPE_ENDPOINT_SECRET
              valueFrom:
                secretKeyRef:
                  key: STRIPE_ENDPOINT_SECRET
                  name: payments-secrets
          resources: {}
status: {}
